// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlCRBAAQ54IKDiL0ejqxJQS9_X4VWQ5Uo',
    appId: '1:487639026647:web:5110d6d2a8ef433e00d992',
    messagingSenderId: '487639026647',
    projectId: 'sipskip-63920',
    authDomain: 'sipskip-63920.firebaseapp.com',
    storageBucket: 'sipskip-63920.firebasestorage.app',
    measurementId: 'G-W1D92NQCR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9P0K_lfgSDGQjVKL8zvEQsImUOP7H-rk',
    appId: '1:487639026647:android:35d15b8b40457cfe00d992',
    messagingSenderId: '487639026647',
    projectId: 'sipskip-63920',
    storageBucket: 'sipskip-63920.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQuPbno9OpEc4qn3XsJNAtat94pNf8GIg',
    appId: '1:487639026647:ios:dff735d956cb1b7900d992',
    messagingSenderId: '487639026647',
    projectId: 'sipskip-63920',
    storageBucket: 'sipskip-63920.firebasestorage.app',
    iosBundleId: 'com.example.appsip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQuPbno9OpEc4qn3XsJNAtat94pNf8GIg',
    appId: '1:487639026647:ios:dff735d956cb1b7900d992',
    messagingSenderId: '487639026647',
    projectId: 'sipskip-63920',
    storageBucket: 'sipskip-63920.firebasestorage.app',
    iosBundleId: 'com.example.appsip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlCRBAAQ54IKDiL0ejqxJQS9_X4VWQ5Uo',
    appId: '1:487639026647:web:9b47a30cef4c541600d992',
    messagingSenderId: '487639026647',
    projectId: 'sipskip-63920',
    authDomain: 'sipskip-63920.firebaseapp.com',
    storageBucket: 'sipskip-63920.firebasestorage.app',
    measurementId: 'G-G7QH461NE8',
  );
}
